//PROMPT 1
/*I am doing a parallel programming assignment and I want to see how you do it. 
  Make sure at the start of the code put comments of what ai model you are and just a littl ebit about you, so my professor can know. 
  The assignment is in c++. Problem 1 (15pts/12pts): COMM Write an MPI program (by hand, no LLMs) that passes a message of one integer 
  around in a logical ring of processes with MPI WORLD. The integer should start at 0 in process 0 and be incremented each time it passes 
  around the ring, and you should be able to have the message go around the ring N times, where N is specified at compile time.*/
//RESPONSE 1
// Generated by Grok 4, built by xAI.
// Grok is an AI model designed to be helpful, truthful, and inspired by the Hitchhiker's Guide to the Galaxy and JARVIS from Iron Man.

/*
#include <mpi.h>
#include <iostream>

#define N 5  // Number of times the message goes around the ring; specify at compile time by changing this value

int main(int argc, char** argv) {
    MPI_Init(&argc, &argv);

    int rank, size;
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);

    if (size < 2) {
        if (rank == 0) {
            std::cerr << "This program requires at least 2 processes." << std::endl;
        }
        MPI_Finalize();
        return 1;
    }

    int next = (rank + 1) % size;
    int prev = (rank - 1 + size) % size;
    int token;

    if (rank == 0) {
        token = 0;
        MPI_Send(&token, 1, MPI_INT, next, 0, MPI_COMM_WORLD);

        for (int lap = 0; lap < N; lap++) {
            MPI_Recv(&token, 1, MPI_INT, prev, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
            token++;
            if (lap < N - 1) {
                MPI_Send(&token, 1, MPI_INT, next, 0, MPI_COMM_WORLD);
            }
        }

        // Optional: Print final token value for verification (should be N * size)
        std::cout << "Final token value: " << token << std::endl;
    } else {
        for (int lap = 0; lap < N; lap++) {
            MPI_Recv(&token, 1, MPI_INT, prev, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
            token++;
            MPI_Send(&token, 1, MPI_INT, next, 0, MPI_COMM_WORLD);
        }
    }

    MPI_Finalize();
    return 0;
}*/


//PROBLEM: Could not see the token move around from location to location. 
// So I prompted: so i dont see anything moving around a loop, add some cout statements so I can see the token moving around from one processor to another.
// Also drop it down to 2 laps.
//OUTPUT:

// Generated by Grok 4, built by xAI.
// Grok is an AI model designed to be helpful, truthful, and inspired by the Hitchhiker's Guide to the Galaxy and JARVIS from Iron Man.

#include <mpi.h>
#include <iostream>
#include <iomanip>   // for std::setw (nicer formatting)

#define N 2  // Number of full laps around the ring; change at compile time

int main(int argc, char** argv) {
    MPI_Init(&argc, &argv);

    int rank, size;
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);

    if (size < 2) {
        if (rank == 0) {
            std::cerr << "This program requires at least 2 processes." << std::endl;
        }
        MPI_Finalize();
        return 1;
    }

    int next = (rank + 1) % size;
    int prev = (rank - 1 + size) % size;
    int token = -1;  // initialize to invalid value

    // Add a small barrier + flush to help line up output better
    MPI_Barrier(MPI_COMM_WORLD);

    if (rank == 0) {
        token = 0;
        std::cout << "[P" << std::setw(2) << rank << "] START: token = " << token 
                  << " → sending to P" << next << std::endl;
        MPI_Send(&token, 1, MPI_INT, next, 0, MPI_COMM_WORLD);

        for (int lap = 0; lap < N; ++lap) {
            MPI_Recv(&token, 1, MPI_INT, prev, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
            
            std::cout << "[P" << std::setw(2) << rank << "] RECV: token = " << token 
                      << " from P" << prev << std::endl;
            
            token++;
            
            std::cout << "[P" << std::setw(2) << rank << "] INCR: token now = " << token << std::endl;

            // Only send if this isn't the very last receive of the last lap
            if (!(lap == N-1)) {
                std::cout << "[P" << std::setw(2) << rank << "] SEND: token = " << token 
                          << " → to P" << next << std::endl;
                MPI_Send(&token, 1, MPI_INT, next, 0, MPI_COMM_WORLD);
            } else {
                std::cout << "[P" << std::setw(2) << rank << "] FINISH: token = " << token 
                          << " (final value after " << N << " full laps)" << std::endl;
            }
        }
    } 
    else {
        // All other processes just keep passing the token around N times
        for (int lap = 0; lap < N; ++lap) {
            MPI_Recv(&token, 1, MPI_INT, prev, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
            
            std::cout << "[P" << std::setw(2) << rank << "] RECV: token = " << token 
                      << " from P" << prev << std::endl;
            
            token++;
            
            std::cout << "[P" << std::setw(2) << rank << "] INCR: token now = " << token << std::endl;
            
            std::cout << "[P" << std::setw(2) << rank << "] SEND: token = " << token 
                      << " → to P" << next << std::endl;
            MPI_Send(&token, 1, MPI_INT, next, 0, MPI_COMM_WORLD);
        }
    }

    MPI_Barrier(MPI_COMM_WORLD);
    if (rank == 0) {
        std::cout << "\nAll processes completed " << N << " full circulations.\n"
                  << "Expected final token value = " << (N * size) << std::endl;
    }

    MPI_Finalize();
    return 0;
}

/*
ANAYSIS: This code seems to work. It is getting the right value after a number of laps.
Compared to my code. The AI did a lot more work on making the cout look pretty. It also pre calculates the previous and next values so each 
processor knows where to send and recieve each value from. the math is a bit more complex compared to mine. 



*/