//PROMPT 1
/*I am doing a parallel programming assignment and I want to see how you do it. 
  Make sure at the start of the code put comments of what ai model you are and just a littl ebit about you, so my professor can know. 
  The assignment is in c++. Write a parallel vector-vector element by element multiplication program (by hand, no LLM) followed by a 
  tree reduction to compute the dot-product of two vectors of length N with P processes using MPI. For instance, show with N = 1024,2048,4096 
  and P = 1,2,4. Use only point-to-point operations. Code your own tree reduction using sends and receives. Divide the data as equally as you can 
  between your processes. We will discuss how to compute these partitions in class early next week (week of February 16). Use MPI Wtime() to measure 
  the cost of the operation as you vary P and N. We will explain how to use this operation in lecture. Use easy-to-evaluate data for testing in the 
  vector elements for correctness testing (but not all zeroes).*/
//ANSWER 1
// Generated by Grok 4, built by xAI.
// Grok is an AI model designed to be helpful, truthful, and inspired by the Hitchhiker's Guide to the Galaxy and JARVIS from Iron Man.

#include <mpi.h>
#include <iostream>
#include <vector>
#include <cstdlib>  // for atoi
#include <iomanip>  // for std::setprecision

int main(int argc, char** argv) {
    MPI_Init(&argc, &argv);

    int rank, size;
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);

    // Assume size is 1, 2, or 4 (power of 2 for tree reduction)
    if (size != 1 && size != 2 && size != 4) {
        if (rank == 0) {
            std::cerr << "This program is designed for P=1,2,4 processes." << std::endl;
        }
        MPI_Finalize();
        return 1;
    }

    // Get N from command line (e.g., mpirun -np 4 ./dot 2048), default 1024
    int N = 1024;
    if (argc > 1) {
        N = std::atoi(argv[1]);
    }

    // Compute local partition (even distribution)
    int base = N / size;
    int rem = N % size;
    int local_size = base + (rank < rem ? 1 : 0);
    int local_start = rank * base + std::min(rank, rem);

    // Local vectors
    std::vector<double> local_A(local_size);
    std::vector<double> local_B(local_size);

    // Root generates full vectors if needed and distributes using point-to-point
    if (rank == 0) {
        std::vector<double> A(N), B(N);
        for (int i = 0; i < N; ++i) {
            A[i] = static_cast<double>(i + 1);       // 1,2,3,...,N
            B[i] = 1.0 / static_cast<double>(i + 1); // 1/1,1/2,...,1/N
            // Each product = 1, total dot product = N (for verification)
        }

        // Copy own local portion
        for (int i = 0; i < local_size; ++i) {
            local_A[i] = A[local_start + i];
            local_B[i] = B[local_start + i];
        }

        // Send to other processes
        for (int p = 1; p < size; ++p) {
            int p_base = N / size;
            int p_rem = N % size;
            int p_size = p_base + (p < p_rem ? 1 : 0);
            int p_start = p * p_base + std::min(p, p_rem);

            MPI_Send(&A[p_start], p_size, MPI_DOUBLE, p, 0, MPI_COMM_WORLD);
            MPI_Send(&B[p_start], p_size, MPI_DOUBLE, p, 1, MPI_COMM_WORLD);
        }
    } else {
        // Receive local portions
        MPI_Recv(local_A.data(), local_size, MPI_DOUBLE, 0, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
        MPI_Recv(local_B.data(), local_size, MPI_DOUBLE, 0, 1, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
    }

    // Barrier to ensure all have data before timing starts
    MPI_Barrier(MPI_COMM_WORLD);

    // Start timing the operation (local compute + reduction)
    double start_time = MPI_Wtime();

    // Local element-wise multiplication and sum (local dot product)
    double local_sum = 0.0;
    for (int i = 0; i < local_size; ++i) {
        local_sum += local_A[i] * local_B[i];
    }

    // Tree reduction (binary tree sum for powers of 2)
    double global_sum = local_sum;
    int step = 1;
    while (step < size) {
        if (rank % (2 * step) == step) {
            // Sender: send to (rank - step)
            MPI_Send(&global_sum, 1, MPI_DOUBLE, rank - step, 0, MPI_COMM_WORLD);
        } else if (rank % (2 * step) == 0 && rank + step < size) {
            // Receiver: recv from (rank + step) and add
            double temp;
            MPI_Recv(&temp, 1, MPI_DOUBLE, rank + step, 0, MPI_COMM_WORLD, MPI_STATUS_IGNORE);
            global_sum += temp;
        }
        step *= 2;
    }

    double end_time = MPI_Wtime();
    double elapsed_time = end_time - start_time;

    // Output results from root (dot product should be N for verification)
    if (rank == 0) {
        std::cout << "N=" << N << ", P=" << size 
                  << ", Time=" << std::setprecision(6) << elapsed_time << " seconds"
                  << ", Dot Product=" << global_sum 
                  << " (expected: " << N << ")" << std::endl;
    }

    MPI_Finalize();
    return 0;
}


//ANALYSIS
/*
This code worked on the first itration from what I can see. Nothing looks out of place.
To start it checks for number of processors, I dont.
I ask for a vector size, so it can be changed every runm then i broadcast to all processes, the ai added it when it runs
My code gets a min and max size and only goes through those values, AI goes through only a local size
I do some math and send code using tree reduction
AI uses the root to send local sizes to all the processrs, each does math, then uses tree reduction to send the information back. 
*/